# Logical Functions in NumPy

![Arithmetic Operations in NumPy](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png)

NumPy offers a versatile set of tools for array creation, enabling users to initialize arrays efficiently with desired shapes, values, and patterns.

These tools support a wide range of initialization methods, from creating arrays filled with zeros or ones to generating evenly spaced sequences, random values, or customized patterns. Functions like `zeros`, `ones`, `arange`, `linspace`, and `random` provide flexibility for diverse use cases, while advanced techniques such as reshaping and broadcasting allow for precise control over array dimensions.

Designed with performance and scalability in mind, NumPy's array creation capabilities form the foundation for numerical computations and data processing tasks.

For more information, see the [NumPy: Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html).


## 1. From Shape or Value

Array creation "From Shape or Value" in NumPy focuses on generating arrays with specific shapes, sizes, or fill values. 
These functions allow for efficient initialization of arrays tailored to various computational needs, from uninitialised 
arrays to those filled with ones, zeros, or custom values.

By using these methods, you can quickly create arrays with predefined characteristics or based on the attributes of 
existing arrays, streamlining workflows for numerical computations and data manipulation.

For more details, see the [Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation).


| Operation             | Function          | Description                                                                 | Documentation                                                                                           |
|-----------------------|-------------------|-----------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------|
| **Uninitialized**     | `np.empty()`      | Creates an uninitialized array of a given shape                             | [Link](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty)                   |
| **Uninitialized**     | `np.empty_like()` | Creates an uninitialized array based on the shape and type of a given array | [Link](https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html#numpy.empty_like)         |
| **Identity Matrix**   | `np.eye()`        | Creates a 2D array with ones on the diagonal and zeros elsewhere            | [Link](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye)                       |
| **Identity Matrix**   | `np.identity()`   | Returns a square identity matrix                                            | [Link](https://numpy.org/doc/stable/reference/generated/numpy.identity.html#numpy.identity)             |
| **Filled with Ones**  | `np.ones()`       | Creates an array filled with ones                                           | [Link](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones)                     |
| **Filled with Ones**  | `np.ones_like()`  | Creates an array of ones based on a reference array                         | [Link](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like)           |
| **Filled with Zeros** | `np.zeros()`      | Creates an array filled with zeros                                          | [Link](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros)                   |
| **Filled with Zeros** | `np.zeros_like()` | Creates an array of zeros based on a reference array                        | [Link](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html#numpy.zeros_like)         |
| **Custom Fill Value** | `np.full()`       | Creates an array filled with a specific value                               | [Link](https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full)                     |
| **Custom Fill Value** | `np.full_like()`  | Creates an array filled with a value based on a reference array             | [Link](https://numpy.org/doc/stable/reference/generated/numpy.full_like.html#numpy.full_like)           |


### 1.1 Empty (np.empty)

The `np.empty()` function in NumPy is used to create a new array of a specified shape and type without initializing its entries. This means that the array will contain arbitrary values (garbage values) based on the memory allocation, making it faster than other initialization methods.

This function is particularly useful for scenarios where array values will be explicitly set later, and the initial content is irrelevant.

**Example:**

In [3]:
import numpy as np

# Create an uninitialized array with shape (2, 3)
uninitialized_array = np.empty((2, 3))

# Create an uninitialized array with a specified data type
uninitialized_float_array = np.empty((2, 3), dtype=float)

# Print the arrays
print("Uninitialized array with shape (2, 3):\n", uninitialized_array)
print("\nUninitialized array with float dtype:\n", uninitialized_float_array)

Uninitialized array with shape (2, 3):
 [[0. 0. 0.]
 [0. 0. 0.]]

Uninitialized array with float dtype:
 [[0. 0. 0.]
 [0. 0. 0.]]


### 1.2 Empty Like (np.empty_like)

The `np.empty_like()` function in NumPy creates a new array with the same shape and type as a specified prototype array. Similar to `np.empty()`, the entries of the array are uninitialized, meaning they contain arbitrary values from memory.

This function is useful when you need to create an uninitialized array that matches the structure of an existing one, saving time and ensuring consistency in shape and type.

**Example:**

In [1]:
import numpy as np

# Define a prototype array
prototype_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create an uninitialized array with the same shape and type as the prototype
uninitialized_like_array = np.empty_like(prototype_array)

# Create an uninitialized array with the same shape but a different data type
uninitialized_float_like_array = np.empty_like(prototype_array, dtype=float)

# Print the arrays
print("Prototype array:\n", prototype_array)
print("\nUninitialized array with the same shape and type:\n", uninitialized_like_array)
print("\nUninitialized array with the same shape but float dtype:\n", uninitialized_float_like_array)

Prototype array:
 [[1 2 3]
 [4 5 6]]

Uninitialized array with the same shape and type:
 [[0 0 0]
 [0 0 0]]

Uninitialized array with the same shape but float dtype:
 [[0. 0. 0.]
 [0. 0. 0.]]


### 1.3 Eye (np.eye)

The `np.eye()` function in NumPy creates a 2-D array with ones on its main diagonal and zeros elsewhere. It is commonly used to generate identity matrices or diagonal matrices for linear algebra operations.

You can specify additional parameters like the number of rows (`N`), the number of columns (`M`), the diagonal offset (`k`), and the data type (`dtype`) to customize the array.

**Example:**

In [1]:
import numpy as np

# Create a square identity matrix of size 3x3
identity_matrix = np.eye(3)

# Create a rectangular matrix with 3 rows and 5 columns
rectangular_matrix = np.eye(3, 5)

# Create a matrix with the diagonal offset by 1 (above the main diagonal)
offset_diagonal_matrix = np.eye(4, k=1)

# Create a matrix with the diagonal offset by -1 (below the main diagonal)
lower_diagonal_matrix = np.eye(4, k=-1)

# Print the matrices
print("3x3 Identity matrix:\n", identity_matrix)
print("\n3x5 Rectangular matrix:\n", rectangular_matrix)
print("\nMatrix with diagonal offset by 1:\n", offset_diagonal_matrix)
print("\nMatrix with diagonal offset by -1:\n", lower_diagonal_matrix)

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x5 Rectangular matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Matrix with diagonal offset by 1:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Matrix with diagonal offset by -1:
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 1.4 Identity (np.identity)

The `np.identity()` function in NumPy creates a square identity matrix of size `n x n`. An identity matrix has ones on its main diagonal and zeros elsewhere, making it useful in various linear algebra applications.

Unlike `np.eye()`, this function always generates a square matrix and does not allow customization of off-diagonal elements or rectangular shapes.

**Example:**

In [2]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix_3x3 = np.identity(3)

# Create a 5x5 identity matrix with float data type
identity_matrix_5x5_float = np.identity(5, dtype=float)

# Print the matrices
print("3x3 Identity matrix:\n", identity_matrix_3x3)
print("\n5x5 Identity matrix with float dtype:\n", identity_matrix_5x5_float)

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

5x5 Identity matrix with float dtype:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 1.5 Ones (np.ones)

The `np.ones()` function in NumPy creates a new array of a specified shape and type, filled entirely with ones. It is commonly used for initializing arrays where a constant value of one is required, such as in computations or as default values.

You can customize the array's data type (`dtype`), memory layout (`order`), and other attributes for flexibility.

**Example:**

In [3]:
import numpy as np

# Create a 2x3 array filled with ones
ones_array = np.ones((2, 3))

# Create a 3x3 array filled with ones and specify the data type as float
ones_float_array = np.ones((3, 3), dtype=float)

# Create a 4x4 array with ones stored in column-major (Fortran-style) order
ones_fortran_array = np.ones((4, 4), order='F')

# Print the arrays
print("2x3 Array filled with ones:\n", ones_array)
print("\n3x3 Array filled with ones (float dtype):\n", ones_float_array)
print("\n4x4 Array filled with ones (Fortran-style order):\n", ones_fortran_array)

2x3 Array filled with ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

3x3 Array filled with ones (float dtype):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

4x4 Array filled with ones (Fortran-style order):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 1.6 Ones Like (np.ones_like)

The `np.ones_like()` function in NumPy creates a new array of ones with the same shape and type as a given array. This function is particularly useful when you need an array filled with ones that matches the structure of an existing array.

You can optionally specify a different data type (`dtype`), memory layout (`order`), or shape to customize the resulting array.

**Example:**

In [4]:
import numpy as np

# Define an existing array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of ones with the same shape and type as the existing array
ones_like_array = np.ones_like(existing_array)

# Create an array of ones with the same shape but specify the data type as float
ones_like_float_array = np.ones_like(existing_array, dtype=float)

# Create an array of ones with a custom shape based on the existing array
ones_like_custom_shape = np.ones_like(existing_array, shape=(3, 2))

# Print the arrays
print("Array of ones with the same shape and type:\n", ones_like_array)
print("\nArray of ones with float dtype:\n", ones_like_float_array)
print("\nArray of ones with custom shape (3x2):\n", ones_like_custom_shape)

Array of ones with the same shape and type:
 [[1 1 1]
 [1 1 1]]

Array of ones with float dtype:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array of ones with custom shape (3x2):
 [[1 1]
 [1 1]
 [1 1]]


### 1.7 Zeros (np.zeros)

The `np.zeros()` function in NumPy creates a new array of a specified shape and type, filled entirely with zeros. This function is commonly used to initialize arrays where a constant value of zero is required, such as in computations or default values.

You can customize the data type (`dtype`), memory layout (`order`), and other attributes for flexibility.

**Example:**

In [7]:
import numpy as np

# Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3))

# Create a 3x3 array filled with zeros and specify the data type as float
zeros_float_array = np.zeros((3, 3), dtype=float)

# Create a 4x4 array with zeros stored in column-major (Fortran-style) order
zeros_fortran_array = np.zeros((4, 4), order='F')

# Print the arrays
print("2x3 Array filled with zeros:\n", zeros_array)
print("\n3x3 Array filled with zeros (float dtype):\n", zeros_float_array)
print("\n4x4 Array filled with zeros (Fortran-style order):\n", zeros_fortran_array)

2x3 Array filled with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

3x3 Array filled with zeros (float dtype):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

4x4 Array filled with zeros (Fortran-style order):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 1.8 Zeros Like (np.zeros_like)

The `np.zeros_like()` function in NumPy creates a new array filled with zeros, matching the shape and type of a specified array. This function is especially useful when you need an array of zeros that conforms to the structure of an existing array.

You can optionally specify a different data type (`dtype`), memory layout (`order`), or shape to customize the resulting array.

**Example:**

In [8]:
import numpy as np

# Define an existing array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of zeros with the same shape and type as the existing array
zeros_like_array = np.zeros_like(existing_array)

# Create an array of zeros with the same shape but specify the data type as float
zeros_like_float_array = np.zeros_like(existing_array, dtype=float)

# Create an array of zeros with a custom shape based on the existing array
zeros_like_custom_shape = np.zeros_like(existing_array, shape=(3, 2))

# Print the arrays
print("Array of zeros with the same shape and type:\n", zeros_like_array)
print("\nArray of zeros with float dtype:\n", zeros_like_float_array)
print("\nArray of zeros with custom shape (3x2):\n", zeros_like_custom_shape)

Array of zeros with the same shape and type:
 [[0 0 0]
 [0 0 0]]

Array of zeros with float dtype:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of zeros with custom shape (3x2):
 [[0 0]
 [0 0]
 [0 0]]


### 1.9 Full (np.full)

The `np.full()` function in NumPy creates a new array of a specified shape and type, filled with a user-defined value (`fill_value`). This method is useful for initializing arrays where all elements need to be set to the same constant value.

You can customize the array's data type (`dtype`), memory layout (`order`), and other attributes to fit specific requirements.

**Example:**

In [9]:
import numpy as np

# Create a 2x3 array filled with the value 7
full_array = np.full((2, 3), 7)

# Create a 4x4 array filled with the value 3.14 and specify the data type as float
full_float_array = np.full((4, 4), 3.14, dtype=float)

# Create a 3x3 array filled with -1 stored in column-major (Fortran-style) order
full_fortran_array = np.full((3, 3), -1, order='F')

# Print the arrays
print("2x3 Array filled with 7:\n", full_array)
print("\n4x4 Array filled with 3.14 (float dtype):\n", full_float_array)
print("\n3x3 Array filled with -1 (Fortran-style order):\n", full_fortran_array)

2x3 Array filled with 7:
 [[7 7 7]
 [7 7 7]]

4x4 Array filled with 3.14 (float dtype):
 [[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]

3x3 Array filled with -1 (Fortran-style order):
 [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


### 1.10 Full Like (np.full_like)

The `np.full_like()` function in NumPy creates a new array filled with a user-defined value (`fill_value`), matching the shape and type of a given array. This method is useful when you need an array initialized with a specific value while preserving the structure of an existing array.

You can optionally specify a different data type (`dtype`), memory layout (`order`), or shape to customize the resulting array.

**Example:**

In [10]:
import numpy as np

# Define an existing array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array filled with the value 7, matching the shape and type of the existing array
full_like_array = np.full_like(existing_array, 7)

# Create an array filled with the value 3.14, matching the shape but specifying the data type as float
full_like_float_array = np.full_like(existing_array, 3.14, dtype=float)

# Create an array filled with the value -1, with a custom shape
full_like_custom_shape = np.full_like(existing_array, -1, shape=(3, 2))

# Print the arrays
print("Array filled with 7, matching shape and type:\n", full_like_array)
print("\nArray filled with 3.14 (float dtype):\n", full_like_float_array)
print("\nArray filled with -1 and custom shape (3x2):\n", full_like_custom_shape)

Array filled with 7, matching shape and type:
 [[7 7 7]
 [7 7 7]]

Array filled with 3.14 (float dtype):
 [[3.14 3.14 3.14]
 [3.14 3.14 3.14]]

Array filled with -1 and custom shape (3x2):
 [[-1 -1]
 [-1 -1]
 [-1 -1]]


## Summary

NumPy's array creation routines are essential for initializing arrays efficiently, catering to various computational and data manipulation needs. These functions provide a foundation for generating arrays with specific values, shapes, and patterns, making them indispensable in tasks ranging from numerical analysis to scientific computing.

Functions like `zeros`, `ones`, `arange`, and `linspace` enable seamless initialization of arrays, while random number generators and reshaping techniques add versatility to array handling. These tools not only simplify the process of creating arrays but also enhance performance when working with large datasets.

In conclusion, NumPy's array creation capabilities empower users to build arrays with precision and efficiency, forming the backbone of effective numerical computations and data processing workflows.
 